### ISSUE TITLE
[Tutorial 9] Watch inode for change

### ISSUE THREAD

**Issue by studersi** [dune73/test-4#56]
The utility `apachex` could be modified to also check the inode of the config file for changes and restart Apache automatically when the configuration file is saved.

The while loop could be modified to work similarly to the one described here:  
https://unix.stackexchange.com/questions/188873/using-inotifywait-along-with-vim/188954#188954

**Comment by dune73** [comment]
That's a nice and welcome idea. Feel free to submit a version that turns on inotify.

**Comment by studersi** [comment]
Moving the discussion to pull request https://github.com/dune73/test-4/pull/75.
