### ISSUE TITLE
[Tutorial 2] Formatting of GitHub markdown is different than on website

### ISSUE THREAD

**Issue by studersi** [dune73/test-4#6]
The problem below only occurs on the website, not on GitHub.

### Formatting: 'module' in italics
`We already compiled all of the modules supplied by Apache in Tutorial 1. We will now be adding the most important ones to our configuration. _mpm_eventmodule and _unixdmodule are needed to operate the server. When compiling in the first tutorial we chose the event process model, which we will now be enabling by loading the module. Of interest: In Apache 2.4 such a fundamental setting as the process model of the server can be set in the configuration. We need the unixd module to run the server (as described above) under the user name we defined.`

See how text is rendered in tutorial. Part of `_mpm_eventmodule` is rendered in italics.

**Comment by dune73** [comment]
That's a bloody nuissance. On top of it: I process the documents with `pandoc` to get a printable PDF that I can then use for teaching. That brings up additional problems at 2-3 locations.

A core issue is that there is no markdown standard. Just varying implementations with undocumented behaviour.

Can you think of a solution that would at least satisfy the website and github?

**Comment by studersi** [comment]
Yes, Markdown can be a nuisance that way.

How are you displaying the markdown on the website, do you convert it to html before uploading?

Since we're already discussing markdown and formatting, I think it could be helpful to to put every sentence on a separate line in the markdown source. They will still be rendered as paragraphs but it makes it much easier for git to merge changes. Pretty much all the merge conflicts we had in the PRs could have been prevented that way. But again, I'm not sure how well that would play with the website.

**Comment by studersi** [comment]
Moving this discussion to PR #84.
